services:

  mlflow-db:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 10s
      retries: 10

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "$MINIO_PORT:9000"
      - "$MINIO_CONSOLE_PORT:$MINIO_CONSOLE_PORT"
    volumes:
      - minio_data:/data
      - ./minio:/minio
      - ./config:/config
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_STORAGE_USE_HTTPS: false
    command: server --console-address ":$MINIO_CONSOLE_PORT" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$MINIO_CONSOLE_PORT/minio/health/live"]
      interval: 2s
      timeout: 10s
      retries: 10

  minio-setup:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./minio:/minio
      - .env:/.env
    entrypoint: /bin/sh
    command: -c "chmod +x /minio/setup.sh && /minio/setup.sh"

  mlflow:
    build:
      context: .
    container_name: mlflow-server
    restart: always
    depends_on:
      mlflow-db: 
        condition: service_healthy
      # minio-setup:
      #   condition: service_completed_successfully
    volumes:
      - ./config:/mlflow/config
    environment:
      MLFLOW_FLASK_SERVER_SECRET_KEY: ${MLFLOW_SECRET_KEY}
      MLFLOW_AUTH_CONFIG_PATH: mlflow/server/auth/basic_auth.ini
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_CONTAINER: ${POSTGRES_CONTAINER}
      MLFLOW_ADMIN_USER: ${MLFLOW_ADMIN_USER}
      MLFLOW_ADMIN_PASSWORD: ${MLFLOW_ADMIN_PASSWORD}
      MLFLOW_TRACKING_URI: "http://localhost:${MLFLOW_PORT}"
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_ADMIN_USER}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_ADMIN_PASSWORD}
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    command: >
      poetry run mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_CONTAINER}:${POSTGRES_PORT}/${POSTGRES_DB}
      --default-artifact-root s3://${MINIO_MLFLOW_BUCKET}
      --host 0.0.0.0
      --port ${MLFLOW_PORT}
      --app-name basic-auth
      
volumes:
  postgres_data: { }
  minio_data: { }
